/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicPokemonsRouteImport } from './routes/(public)/pokemons'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPokemonsRoute = publicPokemonsRouteImport.update({
  id: '/(public)/pokemons',
  path: '/pokemons',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/pokemons': typeof publicPokemonsRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesByTo {
  '/pokemons': typeof publicPokemonsRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/pokemons': typeof publicPokemonsRoute
  '/(public)/': typeof publicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/pokemons' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/pokemons' | '/'
  id: '__root__' | '/(public)/pokemons' | '/(public)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicPokemonsRoute: typeof publicPokemonsRoute
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/pokemons': {
      id: '/(public)/pokemons'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof publicPokemonsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicPokemonsRoute: publicPokemonsRoute,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
