/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicPokemonsRouteImport } from './routes/(public)/pokemons'
import { Route as publicPokemonsPokemonIdRouteImport } from './routes/(public)/pokemons/$pokemonId'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPokemonsRoute = publicPokemonsRouteImport.update({
  id: '/(public)/pokemons',
  path: '/pokemons',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPokemonsPokemonIdRoute = publicPokemonsPokemonIdRouteImport.update({
  id: '/$pokemonId',
  path: '/$pokemonId',
  getParentRoute: () => publicPokemonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/pokemons': typeof publicPokemonsRouteWithChildren
  '/': typeof publicIndexRoute
  '/pokemons/$pokemonId': typeof publicPokemonsPokemonIdRoute
}
export interface FileRoutesByTo {
  '/pokemons': typeof publicPokemonsRouteWithChildren
  '/': typeof publicIndexRoute
  '/pokemons/$pokemonId': typeof publicPokemonsPokemonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/pokemons': typeof publicPokemonsRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(public)/pokemons/$pokemonId': typeof publicPokemonsPokemonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/pokemons' | '/' | '/pokemons/$pokemonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/pokemons' | '/' | '/pokemons/$pokemonId'
  id:
    | '__root__'
    | '/(public)/pokemons'
    | '/(public)/'
    | '/(public)/pokemons/$pokemonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicPokemonsRoute: typeof publicPokemonsRouteWithChildren
  publicIndexRoute: typeof publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/pokemons': {
      id: '/(public)/pokemons'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof publicPokemonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/pokemons/$pokemonId': {
      id: '/(public)/pokemons/$pokemonId'
      path: '/$pokemonId'
      fullPath: '/pokemons/$pokemonId'
      preLoaderRoute: typeof publicPokemonsPokemonIdRouteImport
      parentRoute: typeof publicPokemonsRoute
    }
  }
}

interface publicPokemonsRouteChildren {
  publicPokemonsPokemonIdRoute: typeof publicPokemonsPokemonIdRoute
}

const publicPokemonsRouteChildren: publicPokemonsRouteChildren = {
  publicPokemonsPokemonIdRoute: publicPokemonsPokemonIdRoute,
}

const publicPokemonsRouteWithChildren = publicPokemonsRoute._addFileChildren(
  publicPokemonsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicPokemonsRoute: publicPokemonsRouteWithChildren,
  publicIndexRoute: publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
